spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://winey-zzap.c1gqmrogglzk.ap-northeast-2.rds.amazonaws.com:3306/dev
    username: kwhn
    password: kekkek4463!
  config:
    activate:
      on-profile: dev
